var = [12, 3, 500, -3, 9, 2, 22, 1]
print(var)
ma = max(var)
mi = min(var)
imi = var.index(min(var))
ima = var.index(max(var))
var.remove(mi)
var.remove(ma)
var.insert(imi, ma)
var.insert(ima, mi)
print(var)
