numList = list(map(int, input().split()))
Ma = max(numList)
iMa = numList.index(Ma)
Mi = min(numList)
iMi = numList.index(Mi)

numList.pop(iMa)
numList.insert(iMa, Mi)
numList.pop(iMi)
numList.insert(iMi, Ma)
print(*numList)
